name: make a silly edit

on:
  workflow_dispatch:

jobs:
  edit:
    name: silly edit
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Bump dependencies
        run: echo "silly text" >> silly.txt
      - name: Commit changes
        run: |
          git switch --force-create autodeps/bump_from_${GITHUB_SHA:0:6}
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Dependency updates"
          git push --force --set-upstream origin autodeps/bump_from_${GITHUB_SHA:0:6}
      - name: Make automerge PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # git push returns before github is ready for a pr, we have to poll until success
          for BACKOFF in 1 2 4 8 15 15 15 15 0; do
              sleep $BACKOFF
              if gh pr create \
                --title "Bump dependencies from commit ${GITHUB_SHA:0:6}" \
                --body "" --label dependencies; then
                break
              fi
          done
          (( $BACKOFF )) || echo "Could not create the PR" && false
          # gh pr create returns before the pr is ready, we have to poll until success
          # https://github.com/cli/cli/issues/2619#issuecomment-1240543096        
          for BACKOFF in 1 2 4 8 15 15 15 15; do
              sleep $BACKOFF
              if gh pr merge --auto --squash; then
                  break
              fi
          done
          (( $BACKOFF )) || echo "Could not set automerge" && false
